### ISSUE TITLE
Adding Event Listener

### ISSUE THREAD

**Issue by s-p-a-r-k** [terenceLuffy/AppStoreStyleHorizontalScrollView#11]
Is there a way to add event listener for the horizontal scroll view?
I would like to detect which item in the horizontal scroll view has been touched.

**Comment by terenceLuffy** [comment]
I don't suggest to add a event listener on the scroll view, instead, you should add it to the item you add to the scrollview. For UIButton, you should know..or [UIView](http://stackoverflow.com/questions/4660371/how-to-add-a-touch-event-to-a-uiview)

**Comment by terenceLuffy** [comment]
You can add a touch event to the scroll view just like [UIView](http://stackoverflow.com/questions/4660371/how-to-add-a-touch-event-to-a-uiview)

**Comment by s-p-a-r-k** [comment]
Thank you!
