### ISSUE TITLE
Please update to the latest Swift 3 syntax

### ISSUE THREAD

**Issue by DesmondPang** [terenceLuffy/AppStoreStyleHorizontalScrollView#13]
Please update to the latest Swift 3 syntax

**Comment by terenceLuffy** [comment]
The source has been updated, but Podsepc has some issues on validating the source, I am working on that.

**Comment by terenceLuffy** [comment]
Please don't use the cocoapods to update source for now, their server messed up my pod and it is currently now available, please either download the source directly or use Carthage instead.

**Comment by terenceLuffy** [comment]
Cocoapods fixed the issue, now you can use it to update source.
