### ISSUE TITLE
Center function not working

### ISSUE THREAD

**Issue by ReeceHumphreys** [terenceLuffy/AppStoreStyleHorizontalScrollView#15]
I added the function centerSubviews into ASHorizontalScrollView.swift and in refreshSubviews I added this but elements in the scroll view will still not center. 

```
fileprivate func refreshSubView()
    {
        self.setItemsMarginOnce();
        var itemX = self.leftMarginPx
        for item in self.items
        {
            item.frame = CGRect(x: itemX, y: item.frame.origin.y, width: item.frame.width, height: item.frame.height)
            itemX += item.frame.width + self.itemsMargin
        }
        
        itemX = itemX - self.itemsMargin + self.leftMarginPx;
        self.centerSubviews()
        self.contentSize = CGSize(width: itemX, height: self.frame.size.height)
    }

```

**Comment by terenceLuffy** [comment]
I guess your `refreshSubView` never been called. `refreshSubView` is only called when scrollview's frame changes. In addition to call `centerSubviews` in `refreshSubView`, you should also call it after finishing the setup once.

**Comment by ReeceHumphreys** [comment]
That worked great, thanks for the fast response!
