### ISSUE TITLE
UiView

### ISSUE THREAD

**Issue by AlbertoMrFz** [terenceLuffy/AppStoreStyleHorizontalScrollView#6]
Hi,
As I can add several UIView , which within each UIView has an image and a text below ?

thanks

**Comment by terenceLuffy** [comment]
You need to customize your own UIView, I didn't provide any item template for that.

**Comment by AlbertoMrFz** [comment]
thnk you

**Comment by indrac** [comment]
Can you provide the example of Custom UIView inside the horizontall scrollview?

**Comment by terenceLuffy** [comment]
@indrac I can't give you an example because I don't know what you want. If you have some experience on UIKit, you should know how to do that, because that is just like custom your own UIView/UIViewController in xib or code.

**Comment by indrac** [comment]
I code the layout full code (use SnapKit), but can you give some example the image with some text below the image like the AppStore?

**Comment by terenceLuffy** [comment]
@indrac check here: http://stackoverflow.com/questions/10274859/make-a-custom-view-that-has-a-uiimage-with-a-uilabel-inside-at-bottom-of-image there should have more codes available online, just google it :)
