### ISSUE TITLE
Scroll View

### ISSUE THREAD

**Issue by AlbertoMrFz** [terenceLuffy/AppStoreStyleHorizontalScrollView#7]
hello, I have a problem using this library , the element appear on the right top of the layer of scoll , but left they appear below , as you can make them appear below the layer rather than over ?? Thank you

**Comment by terenceLuffy** [comment]
You may setup the scrollview wrong, please include more detail so that I can see what is your problem.

**Comment by AlbertoMrFz** [comment]
Sorry form mi english but i think that my problem was here:
horizontalScrollView.miniAppearPxOfLastItem = 0
horizontalScrollView.uniformItemSize = CGSizeMake(50, 50)

can you explain me who make this attributes??

**Comment by AlbertoMrFz** [comment]
I just resolve my problem
