### ISSUE TITLE
How To Get Buttons Index

### ISSUE THREAD

**Issue by dowhilenet** [terenceLuffy/AppStoreStyleHorizontalScrollView#9]
Hello, I have a question need to consult

``` swift
            for _ in 0 ... 10 {
                
                let button = UIButton(frame: CGRectZero)
                button.backgroundColor = UIColor.purpleColor()
                button.addTarget(self, action: #selector(tapButton(_:)), forControlEvents: UIControlEvents.TouchUpInside)
                horizontalScrollView.addItem(button)
            }
```

when i touch one button , how to get the button idnex..

😄

**Comment by terenceLuffy** [comment]
You can do it in lots of ways, for example, you can set the tag of button with index like `button.tag = index` or you can get the index from the `items` array using horizontalScrollView.items.indexOf(button)

**Comment by dowhilenet** [comment]
@terenceLuffy thanks
